-- =====================================================
-- 알림 테이블 생성 (TB_NOTIFICATION)
-- =====================================================

-- 테이블이 존재하지 않으면 생성
CREATE TABLE IF NOT EXISTS TB_NOTIFICATION (
    id BIGSERIAL PRIMARY KEY,
    skid VARCHAR(50) NOT NULL,
    gubun VARCHAR(20) NOT NULL,
    project_nm VARCHAR(200) NOT NULL,
    send_yn VARCHAR(1) NOT NULL DEFAULT 'N',
    read_yn VARCHAR(1) NOT NULL DEFAULT 'N',
    create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 인덱스 생성 (조회 성능 향상)
CREATE INDEX IF NOT EXISTS IDX_NOTIFICATION_SKID ON TB_NOTIFICATION(skid);
CREATE INDEX IF NOT EXISTS IDX_NOTIFICATION_CREATE_AT ON TB_NOTIFICATION(create_at DESC);
CREATE INDEX IF NOT EXISTS IDX_NOTIFICATION_SEND_YN ON TB_NOTIFICATION(send_yn);
CREATE INDEX IF NOT EXISTS IDX_NOTIFICATION_READ_YN ON TB_NOTIFICATION(read_yn);
